lib/tom_web/router.ex
defmodule TomWeb.Router do
  use TomWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/projects", ProjectController
    resources "/users", UserController
    resources "/things", ThingController
    resources "/halls", HallController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TomWeb do
  #   pipe_through :api
  # end
end

lib/tom_web/views/thing_view.ex
defmodule TomWeb.ThingView do
  use TomWeb, :view
end

lib/tom_web/templates/thing/edit.html.eex
<h1>Edit Thing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.thing_path(@conn, :update, @thing)) %>

<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>

lib/tom_web/templates/thing/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :users %>
  <%= number_input f, :users %>
  <%= error_tag f, :users %>

  <%= label f, :transactions %>
  <%= number_input f, :transactions %>
  <%= error_tag f, :transactions %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/tom_web/templates/thing/index.html.eex
<h1>Listing Things</h1>

<table>
  <thead>
    <tr>
      <th>Users</th>
      <th>Transactions</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for thing <- @things do %>
    <tr>
      <td><%= thing.users %></td>
      <td><%= thing.transactions %></td>

      <td>
        <%= link "Show", to: Routes.thing_path(@conn, :show, thing) %>
        <%= link "Edit", to: Routes.thing_path(@conn, :edit, thing) %>
        <%= link "Delete", to: Routes.thing_path(@conn, :delete, thing), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Thing", to: Routes.thing_path(@conn, :new) %></span>

lib/tom_web/templates/thing/new.html.eex
<h1>New Thing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.thing_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>

lib/tom_web/templates/thing/show.html.eex
<h1>Show Thing</h1>

<ul>

  <li>
    <strong>Users:</strong>
    <%= @thing.users %>
  </li>

  <li>
    <strong>Transactions:</strong>
    <%= @thing.transactions %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.thing_path(@conn, :edit, @thing) %></span>
<span><%= link "Back", to: Routes.thing_path(@conn, :index) %></span>