lib/tom_web/router.ex
defmodule TomWeb.Router do
  use TomWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/projects", ProjectController
    resources "/users", UserController
    resources "/things", ThingController
    resources "/halls", HallController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TomWeb do
  #   pipe_through :api
  # end
end

lib/tom_web/views/user_view.ex
defmodule TomWeb.UserView do
  use TomWeb, :view
end

lib/tom_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/tom_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :from %>
  <%= text_input f, :from %>
  <%= error_tag f, :from %>

  <%= label f, :to %>
  <%= text_input f, :to %>
  <%= error_tag f, :to %>

  <%= label f, :amount %>
  <%= number_input f, :amount %>
  <%= error_tag f, :amount %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/tom_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.from %></td>
      <td><%= user.to %></td>
      <td><%= user.amount %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/tom_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/tom_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>From:</strong>
    <%= @user.from %>
  </li>

  <li>
    <strong>To:</strong>
    <%= @user.to %>
  </li>

  <li>
    <strong>Amount:</strong>
    <%= @user.amount %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>