lib/tom_web/router.ex
defmodule TomWeb.Router do
  use TomWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/projects", ProjectController
    resources "/users", UserController
    resources "/things", ThingController
    resources "/halls", HallController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TomWeb do
  #   pipe_through :api
  # end
end

lib/tom_web/views/project_view.ex
defmodule TomWeb.ProjectView do
  use TomWeb, :view
end

lib/tom_web/templates/project/edit.html.eex
<h1>Edit Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :update, @project)) %>

<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>

lib/tom_web/templates/project/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/tom_web/templates/project/index.html.eex
<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for project <- @projects do %>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.description %></td>

      <td>
        <%= link "Show", to: Routes.project_path(@conn, :show, project) %>
        <%= link "Edit", to: Routes.project_path(@conn, :edit, project) %>
        <%= link "Delete", to: Routes.project_path(@conn, :delete, project), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Project", to: Routes.project_path(@conn, :new) %></span>

lib/tom_web/templates/project/new.html.eex
<h1>New Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>

lib/tom_web/templates/project/show.html.eex
<h1>Show Project</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @project.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @project.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.project_path(@conn, :edit, @project) %></span>
<span><%= link "Back", to: Routes.project_path(@conn, :index) %></span>